config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/show'

  devise_for :users, :controllers => { :registrations => "registrations" }
  get 'home/index'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    resources :comments, only: [:create, :destroy, :edit, :update]
  end

  resources :visuals, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
         validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_many :comments
end

app/models/visual.rb
class Visual < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 prepend_before_filter :require_no_authentication, :only => [ :new, :create, :cancel ]

  protected

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password, :avatar)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password, :avatar)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="input-field col s3">
    <i class="material-icons prefix">language</i>
    <select id="countries" autofocus>
      <option value="" disabled selected> Choose a country</option>
    </select>
  </div>
  <div id="globe" class="col s10">
  </div>
  <div class="col s2">
    <h5 id="country"></h5>
    <div id="country-info">
    </div>
  </div>
</div>

<h5>NASA Earth Exchange Downscaled Climate Projections, Ensemble Averages for Epicodus</h5>
<form>
  <input id="grouped"type="radio" name="mode" value="grouped">
  <label for="grouped"> Grouped</label>
  <input id="stacked" type="radio" name="mode" value="stacked" checked>
  <label for="stacked"> Stacked</label>
</form>
<svg width="12000" height="500" id="bars"></svg>
<svg id="visualization"></svg>

<h3>IPCC AR4 multi-model average of detrended globally averaged TAS anomalies relative to 1980-1999</h3>
<div id="graph">
  <svg id="stream"></svg>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryMap</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <link href="https://fonts.googleapis.com/css?family=Rubik+Mono+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://d3js.org/d3.v4.min.js"></script>
    <script src="https://d3js.org/topojson.v1.min.js"></script>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <%= link_to "PlanetWatch", root_path, class:"brand-logo" %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">

          <% if user_signed_in? %>
            <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><strong> <%= current_user.username %></strong><i class="material-icons right">arrow_drop_down</i></a></li>
            <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
            <ul id="dropdown1" class="dropdown-content">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li><%= link_to 'Edit Account', edit_user_registration_path, href: '#modal4', class: 'modal-trigger', remote: true %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
           <% else %>
             <li><%= link_to "Login", new_user_session_path, href: '#modal2', class: 'modal-trigger', remote: true %></li>
             <li><%= link_to "About" %></li>
           <% end %>
        </ul>
      </div>
    </nav>

    <div class="container" id="yield">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

    <%= render 'users/registrations/new' %>

    <div id="modal2" class="modal">
      <div class="modal-content">

        <h2 class="center">Login</h2>

        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class="input-field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true %>
          </div>

          <div class="input-field">
            <%= f.label :password %><br />
            <%= f.password_field :password, autocomplete: "off" %>
          </div>

          <% if devise_mapping.rememberable? -%>
            <div class="field">
              <%= f.check_box :remember_me %>
              <%= f.label :remember_me %>
            </div>
          <% end -%>

          <div class="actions">
            <%= f.submit "Log in", class: "btn waves-effect" %>
          </div>
        <% end %>

        <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
        <%= link_to "Need an account? Sign up here.", new_user_registration_path, href: '#modal1', class: 'modal-trigger modal-close', remote: true %><br />
        <% end -%>
        <%= render "users/shared/links" %>

      </div>
    </div>
    <% if current_user %>
      <%= render 'users/registrations/edit' %>
    <% end %>
  </body>

</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/shared/_links.html.erb
<!-- <%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%> -->

<!-- <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_user_registration_path, href: '#modal1', class: 'modal-trigger modal-close', remote: true %><br />
<% end -%> -->

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>